# Missing data and aggregations



In [37]:
import pandas as pd
import numpy as np

np.random.seed(1337)
size = 8

random_matrix = np.random.randint(1, 10, (size, size))
random_matrix


array([[8, 9, 8, 8, 3, 3, 5, 9],
       [7, 7, 8, 9, 2, 7, 7, 3],
       [3, 9, 2, 8, 4, 2, 4, 4],
       [5, 9, 9, 8, 5, 2, 7, 5],
       [5, 3, 6, 8, 5, 3, 4, 3],
       [5, 9, 7, 4, 9, 9, 8, 5],
       [4, 3, 2, 3, 1, 4, 9, 3],
       [2, 1, 2, 5, 3, 1, 1, 8]])

In [38]:
print(f"{random_matrix.size = }")
index = np.random.choice(random_matrix.size, 10, replace=False)
print(f"{index= }")


random_matrix.size = 64
index= array([28, 42, 17, 49, 53, 31, 35,  2, 13, 62])


In [39]:
# random_matrix[5,3] = 999
random_matrix.ravel()


array([8, 9, 8, 8, 3, 3, 5, 9, 7, 7, 8, 9, 2, 7, 7, 3, 3, 9, 2, 8, 4, 2,
       4, 4, 5, 9, 9, 8, 5, 2, 7, 5, 5, 3, 6, 8, 5, 3, 4, 3, 5, 9, 7, 4,
       9, 9, 8, 5, 4, 3, 2, 3, 1, 4, 9, 3, 2, 1, 2, 5, 3, 1, 1, 8])

In [40]:
# type converts it to float so that we can change elements to None
random_matrix = random_matrix * 1.0
random_matrix.ravel()[index] = None
random_matrix


array([[ 8.,  9., nan,  8.,  3.,  3.,  5.,  9.],
       [ 7.,  7.,  8.,  9.,  2., nan,  7.,  3.],
       [ 3., nan,  2.,  8.,  4.,  2.,  4.,  4.],
       [ 5.,  9.,  9.,  8., nan,  2.,  7., nan],
       [ 5.,  3.,  6., nan,  5.,  3.,  4.,  3.],
       [ 5.,  9., nan,  4.,  9.,  9.,  8.,  5.],
       [ 4., nan,  2.,  3.,  1., nan,  9.,  3.],
       [ 2.,  1.,  2.,  5.,  3.,  1., nan,  8.]])

In [41]:
pd.DataFrame(random_matrix)

0    1    2    3    4    5    6    7
0  8.0  9.0  NaN  8.0  3.0  3.0  5.0  9.0
1  7.0  7.0  8.0  9.0  2.0  NaN  7.0  3.0
2  3.0  NaN  2.0  8.0  4.0  2.0  4.0  4.0
3  5.0  9.0  9.0  8.0  NaN  2.0  7.0  NaN
4  5.0  3.0  6.0  NaN  5.0  3.0  4.0  3.0
5  5.0  9.0  NaN  4.0  9.0  9.0  8.0  5.0
6  4.0  NaN  2.0  3.0  1.0  NaN  9.0  3.0
7  2.0  1.0  2.0  5.0  3.0  1.0  NaN  8.0

In [42]:
scores = pd.DataFrame(
    random_matrix,
    index=[f"Player {i}" for i in range(1, size + 1)],
    columns=[f"Round {i}" for i in range(1, size + 1)],
)
scores


Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1      8.0      9.0      NaN      8.0      3.0      3.0      5.0   
Player 2      7.0      7.0      8.0      9.0      2.0      NaN      7.0   
Player 3      3.0      NaN      2.0      8.0      4.0      2.0      4.0   
Player 4      5.0      9.0      9.0      8.0      NaN      2.0      7.0   
Player 5      5.0      3.0      6.0      NaN      5.0      3.0      4.0   
Player 6      5.0      9.0      NaN      4.0      9.0      9.0      8.0   
Player 7      4.0      NaN      2.0      3.0      1.0      NaN      9.0   
Player 8      2.0      1.0      2.0      5.0      3.0      1.0      NaN   

          Round 8  
Player 1      9.0  
Player 2      3.0  
Player 3      4.0  
Player 4      NaN  
Player 5      3.0  
Player 6      5.0  
Player 7      3.0  
Player 8      8.0

## missing data


In [43]:
scores.isnull()

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1    False    False     True    False    False    False    False   
Player 2    False    False    False    False    False     True    False   
Player 3    False     True    False    False    False    False    False   
Player 4    False    False    False    False     True    False    False   
Player 5    False    False    False     True    False    False    False   
Player 6    False    False     True    False    False    False    False   
Player 7    False     True    False    False    False     True    False   
Player 8    False    False    False    False    False    False     True   

          Round 8  
Player 1    False  
Player 2    False  
Player 3    False  
Player 4     True  
Player 5    False  
Player 6    False  
Player 7    False  
Player 8    False

In [44]:
scores.info()

<class 'pandas.core.frame.DataFrame'>
Index: 8 entries, Player 1 to Player 8
Data columns (total 8 columns):
 #   Column   Non-Null Count  Dtype  
---  ------   --------------  -----  
 0   Round 1  8 non-null      float64
 1   Round 2  6 non-null      float64
 2   Round 3  6 non-null      float64
 3   Round 4  7 non-null      float64
 4   Round 5  7 non-null      float64
 5   Round 6  6 non-null      float64
 6   Round 7  7 non-null      float64
 7   Round 8  7 non-null      float64
dtypes: float64(8)
memory usage: 576.0+ bytes


In [45]:
scores

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1      8.0      9.0      NaN      8.0      3.0      3.0      5.0   
Player 2      7.0      7.0      8.0      9.0      2.0      NaN      7.0   
Player 3      3.0      NaN      2.0      8.0      4.0      2.0      4.0   
Player 4      5.0      9.0      9.0      8.0      NaN      2.0      7.0   
Player 5      5.0      3.0      6.0      NaN      5.0      3.0      4.0   
Player 6      5.0      9.0      NaN      4.0      9.0      9.0      8.0   
Player 7      4.0      NaN      2.0      3.0      1.0      NaN      9.0   
Player 8      2.0      1.0      2.0      5.0      3.0      1.0      NaN   

          Round 8  
Player 1      9.0  
Player 2      3.0  
Player 3      4.0  
Player 4      NaN  
Player 5      3.0  
Player 6      5.0  
Player 7      3.0  
Player 8      8.0

In [46]:
scores.dropna()

Empty DataFrame
Columns: [Round 1, Round 2, Round 3, Round 4, Round 5, Round 6, Round 7, Round 8]
Index: []

In [47]:
scores.loc["Player 8"]["Round 7"]= 4

In [48]:
scores

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1      8.0      9.0      NaN      8.0      3.0      3.0      5.0   
Player 2      7.0      7.0      8.0      9.0      2.0      NaN      7.0   
Player 3      3.0      NaN      2.0      8.0      4.0      2.0      4.0   
Player 4      5.0      9.0      9.0      8.0      NaN      2.0      7.0   
Player 5      5.0      3.0      6.0      NaN      5.0      3.0      4.0   
Player 6      5.0      9.0      NaN      4.0      9.0      9.0      8.0   
Player 7      4.0      NaN      2.0      3.0      1.0      NaN      9.0   
Player 8      2.0      1.0      2.0      5.0      3.0      1.0      4.0   

          Round 8  
Player 1      9.0  
Player 2      3.0  
Player 3      4.0  
Player 4      NaN  
Player 5      3.0  
Player 6      5.0  
Player 7      3.0  
Player 8      8.0

In [49]:
scores.dropna() # drops all rows that has a nan

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 8      2.0      1.0      2.0      5.0      3.0      1.0      4.0   

          Round 8  
Player 8      8.0

In [50]:
scores.dropna(axis = "columns", inplace = False)

Round 1  Round 7
Player 1      8.0      5.0
Player 2      7.0      7.0
Player 3      3.0      4.0
Player 4      5.0      7.0
Player 5      5.0      4.0
Player 6      5.0      8.0
Player 7      4.0      9.0
Player 8      2.0      4.0

In [54]:
scores

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1      8.0      9.0      0.0      8.0      3.0      3.0      5.0   
Player 2      7.0      7.0      8.0      9.0      2.0      0.0      7.0   
Player 3      3.0      0.0      2.0      8.0      4.0      2.0      4.0   
Player 4      5.0      9.0      9.0      8.0      0.0      2.0      7.0   
Player 5      5.0      3.0      6.0      0.0      5.0      3.0      4.0   
Player 6      5.0      9.0      0.0      4.0      9.0      9.0      8.0   
Player 7      4.0      0.0      2.0      3.0      1.0      0.0      9.0   
Player 8      2.0      1.0      2.0      5.0      3.0      1.0      4.0   

          Round 8  
Player 1      9.0  
Player 2      3.0  
Player 3      4.0  
Player 4      0.0  
Player 5      3.0  
Player 6      5.0  
Player 7      3.0  
Player 8      8.0

In [52]:
scores.fillna(0, inplace = True) # fills all nulls with zeros

In [53]:
scores

Round 1  Round 2  Round 3  Round 4  Round 5  Round 6  Round 7  \
Player 1      8.0      9.0      0.0      8.0      3.0      3.0      5.0   
Player 2      7.0      7.0      8.0      9.0      2.0      0.0      7.0   
Player 3      3.0      0.0      2.0      8.0      4.0      2.0      4.0   
Player 4      5.0      9.0      9.0      8.0      0.0      2.0      7.0   
Player 5      5.0      3.0      6.0      0.0      5.0      3.0      4.0   
Player 6      5.0      9.0      0.0      4.0      9.0      9.0      8.0   
Player 7      4.0      0.0      2.0      3.0      1.0      0.0      9.0   
Player 8      2.0      1.0      2.0      5.0      3.0      1.0      4.0   

          Round 8  
Player 1      9.0  
Player 2      3.0  
Player 3      4.0  
Player 4      0.0  
Player 5      3.0  
Player 6      5.0  
Player 7      3.0  
Player 8      8.0

## Missing data- strategy


In [55]:
import seaborn as sns
titanic = sns.load_dataset("titanic")
titanic

survived  pclass     sex   age  sibsp  parch     fare embarked   class  \
0           0       3    male  22.0      1      0   7.2500        S   Third   
1           1       1  female  38.0      1      0  71.2833        C   First   
2           1       3  female  26.0      0      0   7.9250        S   Third   
3           1       1  female  35.0      1      0  53.1000        S   First   
4           0       3    male  35.0      0      0   8.0500        S   Third   
..        ...     ...     ...   ...    ...    ...      ...      ...     ...   
886         0       2    male  27.0      0      0  13.0000        S  Second   
887         1       1  female  19.0      0      0  30.0000        S   First   
888         0       3  female   NaN      1      2  23.4500        S   Third   
889         1       1    male  26.0      0      0  30.0000        C   First   
890         0       3    male  32.0      0      0   7.7500        Q   Third   

       who  adult_male deck  embark_town alive  alone  
0      man        True  NaN  Southampton    no  False  
1    woman       False    C    Cherbourg   yes  False  
2    woman       False  NaN  Southampton   yes   True  
3    woman       False    C  Southampton   yes  False  
4      man        True  NaN  Southampton    no   True  
..     ...         ...  ...          ...   ...    ...  
886    man        True  NaN  Southampton    no   True  
887  woman       False    B  Southampton   yes   True  
888  woman       False  NaN  Southampton    no  False  
889    man        True    C    Cherbourg   yes   True  
890    man        True  NaN   Queenstown    no   True  

[891 rows x 15 columns]